### ISSUE TITLE
Unable to compile Demo programs

### ISSUE THREAD

**Issue by RetroNick2020** [wp-xyz/LazBGI#2]
tried cloning and downloading as ZIP

nothing seems to happen when I open the lpi file.

I have tried this with win 10 pro/lazarus 2.0.10.

Just to make sure I tried another Win 10 pc with a fresh install - same issue

I am guessing there may be some hard path set in the search directories for units as part of the project files.

**Comment by RetroNick2020** [comment]
just a bit more info. I created a little work around to figure out if it was your lpi file causing issues.

I renamed simple_demo.lpi to _simple_demo.lpi
create a new project in the same folder
renamed the new project lpi file to simple_demo.lpi
from the project options I added all files in the directory to the project.

I was able to compile and run the demo after that so there is something in the lpi file thats causing some kind of issue.

**Comment by wp-xyz** [comment]
I had developed these demos with Laz-trunk which writes xml files in a different format, and had forgotten to activate the compatibility mode in the project options to write them in the old format.

Fixed

When this happens to you once more you could use the fixlp tool on CCR (https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/applications/fixlp/) to convert to the old format. Or switch to Laz 2.2 which reads/writes the new format by default.

**Comment by RetroNick2020** [comment]
> I had developed these demos with Laz-trunk which writes xml files in a different format, and had forgotten to activate the compatibility mode in the project options to write them in the old format.
> 
> Fixed
> 
> When this happens to you once more you could use the fixlp tool on CCR (https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/applications/fixlp/) to convert to the old format. Or switch to Laz 2.2 which reads/writes the new format by default.

hey that's great - thanks for fixing so quickly.
